# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6333a4363ac89fea0b771781b40e2fa433aeee06f740ceda9e0f4431af84758c74670043c0a0c33cac64b7f3a03e3d82e6fa4a1dbd7f7ebc96fdc4097c2dcbfc

test:
  secret_key_base: 5286ad0c70778f2b058a6a84592b6b79fb5ebbe7e8fb939a37f7611f781c1d51b73bd141e752e4ce5a4c066fc2909ff3db49039d40b678b5bf9346c112c733d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
